"""
Protected bundle runtime loader.

Loads and extracts Qyro's protected resources package generated by qyro-cli,
making embedded settings/ and resources/ folders available through filesystem
paths without changing existing public APIs.
"""

from __future__ import annotations

import hashlib
import hmac
import importlib.util
import io
import tempfile
import zipfile
from importlib.machinery import ExtensionFileLoader
from pathlib import Path
from threading import Lock

from qyro.application.ports.environment import IEnvironmentPort


_MAGIC = b"QYRPKG"
_NONCE_LEN = 16
_SALT_LEN = 16
_TAG_LEN = 32
_KEY_LEN = 32
_RUNTIME_SECRET_MODULE_STEM = "runtime"


class ProtectedResourceBundle:
    """Utility that extracts protected bundle contents when available."""

    _lock = Lock()
    _extracted_cache: dict[str, Path] = {}

    @classmethod
    def get_extracted_root(cls, env_port: IEnvironmentPort) -> Path | None:
        """Return extracted root containing settings/ and resources/ when present."""
        base_dir = env_port.get_bundle_dir() if env_port.is_frozen() else env_port.get_root_dir()
        package_path = base_dir / ".qyro" / "protected_resources.pak"
        secret_module_path = cls._find_runtime_secret_module(base_dir / ".qyro")

        if not package_path.exists() or secret_module_path is None:
            return None

        cache_key = cls._cache_key(package_path, secret_module_path)
        with cls._lock:
            cached = cls._extracted_cache.get(cache_key)
            if cached and cached.exists():
                return cached
            try:
                extracted_root = cls._extract_bundle(package_path, secret_module_path)
            except Exception:
                return None
            cls._extracted_cache[cache_key] = extracted_root
            return extracted_root

    @staticmethod
    def _find_runtime_secret_module(qyro_dir: Path) -> Path | None:
        candidates = [
            *sorted(qyro_dir.glob(f"{_RUNTIME_SECRET_MODULE_STEM}*.so")),
            *sorted(qyro_dir.glob(f"{_RUNTIME_SECRET_MODULE_STEM}*.pyd")),
            *sorted(qyro_dir.glob(f"{_RUNTIME_SECRET_MODULE_STEM}*.dylib")),
        ]
        for candidate in candidates:
            if candidate.is_file():
                return candidate
        return None

    @staticmethod
    def _cache_key(package_path: Path, secret_module_path: Path) -> str:
        stat_a = package_path.stat()
        stat_b = secret_module_path.stat()
        return (
            f"{package_path}:{stat_a.st_mtime_ns}:{stat_a.st_size}:"
            f"{secret_module_path}:{stat_b.st_mtime_ns}:{stat_b.st_size}"
        )

    @classmethod
    def _extract_bundle(cls, package_path: Path, secret_module_path: Path) -> Path:
        payload = package_path.read_bytes()
        runtime_secret = cls._read_runtime_secret(secret_module_path)
        key, ciphertext, nonce, tag = cls._parse_payload(payload, runtime_secret)

        expected_tag = hmac.new(key, nonce + ciphertext, hashlib.sha256).digest()
        if not hmac.compare_digest(tag, expected_tag):
            raise ValueError("Protected resources signature mismatch")

        zip_bytes = cls._xor_keystream(ciphertext, key=key, nonce=nonce)
        digest = hashlib.sha256(payload).hexdigest()[:16]
        extract_root = Path(tempfile.gettempdir()) / f"qyro_protected_{digest}"

        marker = extract_root / ".ok"
        if marker.exists():
            return extract_root

        extract_root.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as archive:
            archive.extractall(extract_root)

        marker.write_text("ok", encoding="utf-8")
        return extract_root

    @classmethod
    def _parse_payload(cls, payload: bytes, runtime_secret: bytes) -> tuple[bytes, bytes, bytes, bytes]:
        min_len = len(_MAGIC) + _SALT_LEN + _KEY_LEN + _NONCE_LEN + _TAG_LEN
        if len(payload) <= min_len or not payload.startswith(_MAGIC):
            raise ValueError("Invalid protected resources package format")

        cursor = len(_MAGIC)
        salt = payload[cursor:cursor + _SALT_LEN]
        cursor += _SALT_LEN

        wrapped_key = payload[cursor:cursor + _KEY_LEN]
        cursor += _KEY_LEN

        nonce = payload[cursor:cursor + _NONCE_LEN]
        cursor += _NONCE_LEN

        tag = payload[cursor:cursor + _TAG_LEN]
        cursor += _TAG_LEN

        ciphertext = payload[cursor:]
        key = cls._unwrap_key(wrapped_key=wrapped_key, salt=salt, runtime_secret=runtime_secret)
        return key, ciphertext, nonce, tag

    @classmethod
    def _unwrap_key(cls, *, wrapped_key: bytes, salt: bytes, runtime_secret: bytes) -> bytes:
        mask = cls._keystream(seed=cls._master_seed(salt, runtime_secret), size=len(wrapped_key))
        return bytes(value ^ mask[i] for i, value in enumerate(wrapped_key))

    @staticmethod
    def _master_seed(salt: bytes, runtime_secret: bytes) -> bytes:
        return hashlib.sha256(runtime_secret + salt).digest()

    @classmethod
    def _keystream(cls, *, seed: bytes, size: int) -> bytes:
        blocks: list[bytes] = []
        index = 0
        total = 0
        while total < size:
            block = hashlib.sha256(seed + index.to_bytes(8, "big")).digest()
            blocks.append(block)
            total += len(block)
            index += 1
        return b"".join(blocks)[:size]

    @staticmethod
    def _read_runtime_secret(secret_module_path: Path) -> bytes:
        module_name = _RUNTIME_SECRET_MODULE_STEM
        loader = ExtensionFileLoader(module_name, str(secret_module_path))
        spec = importlib.util.spec_from_file_location(module_name, str(secret_module_path), loader=loader)
        if spec is None:
            raise ValueError("Unable to load runtime secret module spec")
        module = importlib.util.module_from_spec(spec)
        loader.exec_module(module)

        value = getattr(module, "RUNTIME_SECRET_HEX", None)
        if not isinstance(value, str) or not value.strip():
            raise ValueError("Runtime secret not found in runtime module")

        try:
            secret = bytes.fromhex(value.strip())
        except ValueError as exc:
            raise ValueError("Invalid runtime secret hex format") from exc

        if len(secret) < 16:
            raise ValueError("Runtime secret is too short")

        return secret

    @staticmethod
    def _xor_keystream(data: bytes, *, key: bytes, nonce: bytes) -> bytes:
        out = bytearray(len(data))
        block_index = 0
        offset = 0

        while offset < len(data):
            block_seed = nonce + block_index.to_bytes(8, "big")
            stream = hashlib.sha256(key + block_seed).digest()
            chunk = data[offset:offset + len(stream)]

            for i, value in enumerate(chunk):
                out[offset + i] = value ^ stream[i]

            offset += len(chunk)
            block_index += 1

        return bytes(out)
