"""
Protected bundle runtime loader.

Loads and extracts Qyro's protected resources package generated by qyro-cli,
making embedded settings/ and resources/ folders available through filesystem
paths without changing existing public APIs.
"""

from __future__ import annotations

import hashlib
import hmac
import io
import tempfile
import zipfile
from pathlib import Path
from threading import Lock

from qyro.application.ports.environment import IEnvironmentPort
from qyro.adapters.resources.runtime_secret import (
    find_runtime_secret_module,
    read_runtime_secret,
)


_MAGIC = b"QYRPKG"
_NONCE_LEN = 16
_SALT_LEN = 16
_TAG_LEN = 32
_KEY_LEN = 32
_RUNTIME_SECRET_MODULE_STEM = "runtime"
_SECRETS_ARCHIVE_PATH = ".qyro/secrets.enc"


class ProtectedResourceBundle:
    """Utility that extracts protected bundle contents when available."""

    _lock = Lock()
    _extracted_cache: dict[str, Path] = {}
    _encrypted_secrets_cache: dict[str, bytes | None] = {}

    @classmethod
    def get_extracted_root(cls, env_port: IEnvironmentPort) -> Path | None:
        """Return extracted root containing settings/ and resources/ when present."""
        base_dir = env_port.get_bundle_dir() if env_port.is_frozen() else env_port.get_root_dir()
        package_path = base_dir / ".qyro" / "protected_resources.pak"
        secret_module_path = cls._find_runtime_secret_module(base_dir / ".qyro")

        if not package_path.exists() or secret_module_path is None:
            return None

        cache_key = cls._cache_key(package_path, secret_module_path)
        with cls._lock:
            cached = cls._extracted_cache.get(cache_key)
            if cached and cached.exists():
                return cached
            try:
                extracted_root, encrypted_payload = cls._extract_bundle(package_path, secret_module_path)
            except Exception:
                return None
            cls._extracted_cache[cache_key] = extracted_root
            cls._encrypted_secrets_cache[cache_key] = encrypted_payload
            return extracted_root

    @classmethod
    def get_encrypted_secrets_payload(cls, env_port: IEnvironmentPort) -> bytes | None:
        """Return encrypted secrets payload embedded in protected_resources.pak when available."""
        base_dir = env_port.get_bundle_dir() if env_port.is_frozen() else env_port.get_root_dir()
        package_path = base_dir / ".qyro" / "protected_resources.pak"
        secret_module_path = cls._find_runtime_secret_module(base_dir / ".qyro")

        if not package_path.exists() or secret_module_path is None:
            return None

        cache_key = cls._cache_key(package_path, secret_module_path)
        with cls._lock:
            if cache_key in cls._encrypted_secrets_cache:
                return cls._encrypted_secrets_cache[cache_key]

            try:
                extracted_root, encrypted_payload = cls._extract_bundle(package_path, secret_module_path)
            except Exception:
                return None

            cls._extracted_cache[cache_key] = extracted_root
            cls._encrypted_secrets_cache[cache_key] = encrypted_payload
            return encrypted_payload

    @staticmethod
    def _find_runtime_secret_module(qyro_dir: Path) -> Path | None:
        return find_runtime_secret_module(qyro_dir)

    @staticmethod
    def _cache_key(package_path: Path, secret_module_path: Path) -> str:
        stat_a = package_path.stat()
        stat_b = secret_module_path.stat()
        return (
            f"{package_path}:{stat_a.st_mtime_ns}:{stat_a.st_size}:"
            f"{secret_module_path}:{stat_b.st_mtime_ns}:{stat_b.st_size}"
        )

    @classmethod
    def _extract_bundle(cls, package_path: Path, secret_module_path: Path) -> tuple[Path, bytes | None]:
        zip_bytes = cls._decrypt_package_to_zip_bytes(package_path, secret_module_path)
        digest = hashlib.sha256(package_path.read_bytes()).hexdigest()[:16]
        extract_root = Path(tempfile.gettempdir()) / f"qyro_protected_{digest}"
        encrypted_secrets_payload = cls._read_embedded_secrets_payload(zip_bytes)

        marker = extract_root / ".ok"
        if marker.exists():
            return extract_root, encrypted_secrets_payload

        extract_root.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as archive:
            for member in archive.infolist():
                normalized_name = member.filename.strip("/")
                if not normalized_name:
                    continue
                if normalized_name == _SECRETS_ARCHIVE_PATH:
                    continue
                if normalized_name.startswith(".qyro/"):
                    continue
                archive.extract(member, extract_root)

        marker.write_text("ok", encoding="utf-8")
        return extract_root, encrypted_secrets_payload

    @classmethod
    def _decrypt_package_to_zip_bytes(cls, package_path: Path, secret_module_path: Path) -> bytes:
        payload = package_path.read_bytes()
        runtime_secret = cls._read_runtime_secret(secret_module_path)
        key, ciphertext, nonce, tag = cls._parse_payload(payload, runtime_secret)

        expected_tag = hmac.new(key, nonce + ciphertext, hashlib.sha256).digest()
        if not hmac.compare_digest(tag, expected_tag):
            raise ValueError("Protected resources signature mismatch")

        return cls._xor_keystream(ciphertext, key=key, nonce=nonce)

    @staticmethod
    def _read_embedded_secrets_payload(zip_bytes: bytes) -> bytes | None:
        with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as archive:
            try:
                return archive.read(_SECRETS_ARCHIVE_PATH)
            except KeyError:
                return None

    @classmethod
    def _parse_payload(cls, payload: bytes, runtime_secret: bytes) -> tuple[bytes, bytes, bytes, bytes]:
        min_len = len(_MAGIC) + _SALT_LEN + _KEY_LEN + _NONCE_LEN + _TAG_LEN
        if len(payload) <= min_len or not payload.startswith(_MAGIC):
            raise ValueError("Invalid protected resources package format")

        cursor = len(_MAGIC)
        salt = payload[cursor:cursor + _SALT_LEN]
        cursor += _SALT_LEN

        wrapped_key = payload[cursor:cursor + _KEY_LEN]
        cursor += _KEY_LEN

        nonce = payload[cursor:cursor + _NONCE_LEN]
        cursor += _NONCE_LEN

        tag = payload[cursor:cursor + _TAG_LEN]
        cursor += _TAG_LEN

        ciphertext = payload[cursor:]
        key = cls._unwrap_key(wrapped_key=wrapped_key, salt=salt, runtime_secret=runtime_secret)
        return key, ciphertext, nonce, tag

    @classmethod
    def _unwrap_key(cls, *, wrapped_key: bytes, salt: bytes, runtime_secret: bytes) -> bytes:
        mask = cls._keystream(seed=cls._master_seed(salt, runtime_secret), size=len(wrapped_key))
        return bytes(value ^ mask[i] for i, value in enumerate(wrapped_key))

    @staticmethod
    def _master_seed(salt: bytes, runtime_secret: bytes) -> bytes:
        return hashlib.sha256(runtime_secret + salt).digest()

    @classmethod
    def _keystream(cls, *, seed: bytes, size: int) -> bytes:
        blocks: list[bytes] = []
        index = 0
        total = 0
        while total < size:
            block = hashlib.sha256(seed + index.to_bytes(8, "big")).digest()
            blocks.append(block)
            total += len(block)
            index += 1
        return b"".join(blocks)[:size]

    @staticmethod
    def _read_runtime_secret(secret_module_path: Path) -> bytes:
        return read_runtime_secret(secret_module_path)

    @staticmethod
    def _xor_keystream(data: bytes, *, key: bytes, nonce: bytes) -> bytes:
        out = bytearray(len(data))
        block_index = 0
        offset = 0

        while offset < len(data):
            block_seed = nonce + block_index.to_bytes(8, "big")
            stream = hashlib.sha256(key + block_seed).digest()
            chunk = data[offset:offset + len(stream)]

            for i, value in enumerate(chunk):
                out[offset + i] = value ^ stream[i]

            offset += len(chunk)
            block_index += 1

        return bytes(out)
