from __future__ import annotations

import hashlib
import hmac
import io
import json
import subprocess
import sys
import secrets
import zipfile
from pathlib import Path

import pytest

from qyro.adapters.environment.system_environment import SystemEnvironmentAdapter
from qyro.adapters.resources.filesystem_resources import FileSystemResourceAdapter
from qyro.adapters.resources.protected_bundle import ProtectedResourceBundle
from qyro.adapters.resources.secrets_crypto import encrypt_secrets_payload
from qyro.adapters.settings.json_settings import JsonSettingsAdapter
from qyro.domain.entities import ResourceQuery


_MAGIC = b"QYRPKG"


def _xor_keystream(data: bytes, *, key: bytes, nonce: bytes) -> bytes:
    out = bytearray(len(data))
    block_index = 0
    offset = 0

    while offset < len(data):
        block_seed = nonce + block_index.to_bytes(8, "big")
        stream = hashlib.sha256(key + block_seed).digest()
        chunk = data[offset:offset + len(stream)]
        for i, value in enumerate(chunk):
            out[offset + i] = value ^ stream[i]
        offset += len(chunk)
        block_index += 1

    return bytes(out)


def _wrap_key(resource_key: bytes, salt: bytes, runtime_secret: bytes) -> bytes:
    seed = hashlib.sha256(runtime_secret + salt).digest()
    blocks = []
    index = 0
    total = 0
    while total < len(resource_key):
        block = hashlib.sha256(seed + index.to_bytes(8, "big")).digest()
        blocks.append(block)
        total += len(block)
        index += 1
    mask = b"".join(blocks)[:len(resource_key)]
    return bytes(value ^ mask[i] for i, value in enumerate(resource_key))


def _write_protected_package(
    project_root: Path,
    *,
    embedded_secrets_payload: bytes | None = None,
    runtime_secret: bytes | None = None,
) -> bytes:
    qyro_dir = project_root / ".qyro"
    qyro_dir.mkdir(parents=True, exist_ok=True)

    runtime_secret_value = runtime_secret or secrets.token_bytes(32)
    runtime_secret_source = qyro_dir / "runtime.py"
    runtime_secret_source.write_text(
        "# Auto-generated by test\n"
        f"RUNTIME_SECRET_HEX = \"{runtime_secret_value.hex()}\"\n",
        encoding="utf-8",
    )

    proc = subprocess.run(
        [sys.executable, "-m", "Cython.Build.Cythonize", "-3", "-i", runtime_secret_source.name],
        cwd=str(qyro_dir),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError("cythonize failed in test fixture")

    runtime_candidates = list(qyro_dir.glob("runtime*.so")) + list(qyro_dir.glob("runtime*.pyd"))
    if not runtime_candidates:
        raise RuntimeError("compiled runtime module not found")

    (qyro_dir / "runtime.c").unlink(missing_ok=True)
    runtime_secret_source.unlink(missing_ok=True)

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("settings/base.json", '{"app_name": "ProtectedApp", "feature": true}')
        archive.writestr("resources/images/logo.png", "png")
        if embedded_secrets_payload is not None:
            archive.writestr(".qyro/secrets.enc", embedded_secrets_payload)

    payload = buffer.getvalue()
    key = secrets.token_bytes(32)
    salt = secrets.token_bytes(16)
    wrapped_key = _wrap_key(key, salt, runtime_secret_value)
    nonce = secrets.token_bytes(16)
    ciphertext = _xor_keystream(payload, key=key, nonce=nonce)
    tag = hmac.new(key, nonce + ciphertext, hashlib.sha256).digest()

    (qyro_dir / "protected_resources.pak").write_bytes(
        _MAGIC + salt + wrapped_key + nonce + tag + ciphertext
    )
    return runtime_secret_value


def test_json_settings_adapter_loads_base_from_protected_package(tmp_path: Path) -> None:
    _write_protected_package(tmp_path)
    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    adapter = JsonSettingsAdapter(env)

    raw = adapter.get_raw_settings()

    assert raw["app_name"] == "ProtectedApp"
    assert raw["feature"] is True


def test_json_settings_adapter_does_not_load_sign_profile(tmp_path: Path) -> None:
    settings_dir = tmp_path / "settings"
    settings_dir.mkdir()
    (settings_dir / "base.json").write_text(
        '{"app_name": "RuntimeApp"}',
        encoding="utf-8",
    )
    (settings_dir / "sign.json").write_text(
        '{"sign": {"windows": {"password": "signing-only"}}}',
        encoding="utf-8",
    )

    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    adapter = JsonSettingsAdapter(env)

    raw = adapter.get_raw_settings()

    assert raw["app_name"] == "RuntimeApp"
    assert "sign" not in raw


def test_filesystem_resource_adapter_resolves_file_from_protected_package(tmp_path: Path) -> None:
    _write_protected_package(tmp_path)
    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    adapter = FileSystemResourceAdapter(env)

    result = adapter.resolve(ResourceQuery.from_segments("images", "logo.png"))

    assert result.exists is True
    assert result.absolute_path.exists() is True
    assert result.absolute_path.name == "logo.png"


def test_json_settings_adapter_applies_encrypted_secrets_override(tmp_path: Path) -> None:
    runtime_secret = _write_protected_package(tmp_path)
    secrets_payload = encrypt_secrets_payload(
        json.dumps({"feature": False, "api": {"token": "runtime-secret"}}).encode("utf-8"),
        runtime_secret,
    )
    _write_protected_package(
        tmp_path,
        embedded_secrets_payload=secrets_payload,
        runtime_secret=runtime_secret,
    )

    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    adapter = JsonSettingsAdapter(env)

    raw = adapter.get_raw_settings()

    assert raw["feature"] is False
    assert raw["api"] == {"token": "runtime-secret"}


def test_json_settings_adapter_rejects_invalid_encrypted_json(tmp_path: Path) -> None:
    runtime_secret = _write_protected_package(tmp_path)
    _write_protected_package(
        tmp_path,
        embedded_secrets_payload=encrypt_secrets_payload(b"", runtime_secret),
        runtime_secret=runtime_secret,
    )

    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    adapter = JsonSettingsAdapter(env)

    with pytest.raises(ValueError):
        _ = adapter.get_raw_settings()


def test_runtime_does_not_extract_embedded_secrets_payload(tmp_path: Path) -> None:
    runtime_secret = _write_protected_package(tmp_path)
    secrets_payload = encrypt_secrets_payload(
        json.dumps({"api": {"token": "runtime-secret"}}).encode("utf-8"),
        runtime_secret,
    )
    _write_protected_package(
        tmp_path,
        embedded_secrets_payload=secrets_payload,
        runtime_secret=runtime_secret,
    )

    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    extracted_root = ProtectedResourceBundle.get_extracted_root(env)

    assert extracted_root is not None
    assert not (extracted_root / ".qyro" / "secrets.enc").exists()
    assert not (extracted_root / "secrets.json").exists()


def test_runtime_rejects_tampered_embedded_secrets_payload(tmp_path: Path) -> None:
    runtime_secret = _write_protected_package(tmp_path)
    payload = bytearray(
        encrypt_secrets_payload(
            json.dumps({"api": {"token": "runtime-secret"}}).encode("utf-8"),
            runtime_secret,
        )
    )
    payload[-1] ^= 0x01
    _write_protected_package(
        tmp_path,
        embedded_secrets_payload=bytes(payload),
        runtime_secret=runtime_secret,
    )

    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    adapter = JsonSettingsAdapter(env)

    with pytest.raises(ValueError):
        _ = adapter.get_raw_settings()


def test_runtime_rejects_tampered_protected_package_integrity(tmp_path: Path) -> None:
    _write_protected_package(tmp_path)
    pak_path = tmp_path / ".qyro" / "protected_resources.pak"
    tampered = bytearray(pak_path.read_bytes())
    tampered[-1] ^= 0x01
    pak_path.write_bytes(bytes(tampered))

    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    adapter = JsonSettingsAdapter(env)

    raw = adapter.get_raw_settings()
    assert "app_name" not in raw


def test_runtime_supports_legacy_external_encrypted_secrets_file(tmp_path: Path) -> None:
    runtime_secret = _write_protected_package(tmp_path)
    legacy_path = tmp_path / ".qyro" / "secrets.json"
    legacy_path.write_bytes(
        encrypt_secrets_payload(
            json.dumps({"api": {"token": "legacy-secret"}}).encode("utf-8"),
            runtime_secret,
        )
    )

    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    adapter = JsonSettingsAdapter(env)

    raw = adapter.get_raw_settings()
    assert raw["api"] == {"token": "legacy-secret"}
