from __future__ import annotations

import hashlib
import hmac
import io
import subprocess
import sys
import secrets
import zipfile
from pathlib import Path

from qyro.adapters.environment.system_environment import SystemEnvironmentAdapter
from qyro.adapters.resources.filesystem_resources import FileSystemResourceAdapter
from qyro.adapters.settings.json_settings import JsonSettingsAdapter
from qyro.domain.entities import ResourceQuery


_MAGIC = b"QYRPKG"


def _xor_keystream(data: bytes, *, key: bytes, nonce: bytes) -> bytes:
    out = bytearray(len(data))
    block_index = 0
    offset = 0

    while offset < len(data):
        block_seed = nonce + block_index.to_bytes(8, "big")
        stream = hashlib.sha256(key + block_seed).digest()
        chunk = data[offset:offset + len(stream)]
        for i, value in enumerate(chunk):
            out[offset + i] = value ^ stream[i]
        offset += len(chunk)
        block_index += 1

    return bytes(out)


def _wrap_key(resource_key: bytes, salt: bytes, runtime_secret: bytes) -> bytes:
    seed = hashlib.sha256(runtime_secret + salt).digest()
    blocks = []
    index = 0
    total = 0
    while total < len(resource_key):
        block = hashlib.sha256(seed + index.to_bytes(8, "big")).digest()
        blocks.append(block)
        total += len(block)
        index += 1
    mask = b"".join(blocks)[:len(resource_key)]
    return bytes(value ^ mask[i] for i, value in enumerate(resource_key))


def _write_protected_package(project_root: Path) -> None:
    qyro_dir = project_root / ".qyro"
    qyro_dir.mkdir(parents=True, exist_ok=True)

    runtime_secret = secrets.token_bytes(32)
    runtime_secret_source = qyro_dir / "runtime.py"
    runtime_secret_source.write_text(
        "# Auto-generated by test\n"
        f"RUNTIME_SECRET_HEX = \"{runtime_secret.hex()}\"\n",
        encoding="utf-8",
    )

    proc = subprocess.run(
        [sys.executable, "-m", "cythonize", "-3", "-i", runtime_secret_source.name],
        cwd=str(qyro_dir),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError("cythonize failed in test fixture")

    runtime_candidates = list(qyro_dir.glob("runtime*.so")) + list(qyro_dir.glob("runtime*.pyd"))
    if not runtime_candidates:
        raise RuntimeError("compiled runtime module not found")

    (qyro_dir / "runtime.c").unlink(missing_ok=True)
    runtime_secret_source.unlink(missing_ok=True)

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("settings/base.json", '{"app_name": "ProtectedApp", "feature": true}')
        archive.writestr("resources/images/logo.png", "png")

    payload = buffer.getvalue()
    key = secrets.token_bytes(32)
    salt = secrets.token_bytes(16)
    wrapped_key = _wrap_key(key, salt, runtime_secret)
    nonce = secrets.token_bytes(16)
    ciphertext = _xor_keystream(payload, key=key, nonce=nonce)
    tag = hmac.new(key, nonce + ciphertext, hashlib.sha256).digest()

    (qyro_dir / "protected_resources.pak").write_bytes(
        _MAGIC + salt + wrapped_key + nonce + tag + ciphertext
    )


def test_json_settings_adapter_loads_base_from_protected_package(tmp_path: Path) -> None:
    _write_protected_package(tmp_path)
    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    adapter = JsonSettingsAdapter(env)

    raw = adapter.get_raw_settings()

    assert raw["app_name"] == "ProtectedApp"
    assert raw["feature"] is True


def test_filesystem_resource_adapter_resolves_file_from_protected_package(tmp_path: Path) -> None:
    _write_protected_package(tmp_path)
    env = SystemEnvironmentAdapter(custom_root=tmp_path)
    adapter = FileSystemResourceAdapter(env)

    result = adapter.resolve(ResourceQuery.from_segments("images", "logo.png"))

    assert result.exists is True
    assert result.absolute_path.exists() is True
    assert result.absolute_path.name == "logo.png"
